### ISSUE TITLE
Doesn't export any icons

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.elementary.code#2]
This doesn't show up in the [beta web apps](https://beta.flathub.org/apps) view because it doesn't export any icons, [2.4.1 uses an icon from the icon theme](https://github.com/elementary/code/tree/33992888cb4353958e113029769acba73d5c4fb1) (accessories-text-editor). Upstream has done a lot of work since then, [there are icons now!](https://github.com/elementary/code/tree/master/data) The app name and indeed purpose has changed. Do we know when a new release is planned?

**Comment by Alexander-Wilms** [comment]
I've updated it to the latest commit. The next release can't be too far off, since the milestone is 91% complete: https://github.com/elementary/code/milestone/1
