### ISSUE TITLE
UserWarning: No base given

### ISSUE THREAD

**Issue by deikatsuo** [flathub/io.elementary.code#5]
Stuck here
![screenshot from 2018-01-20 07-35-58](https://user-images.githubusercontent.com/8337409/35177758-ad617724-fdb4-11e7-9a30-195ed1109ea7.png)

**Comment by Alexander-Wilms** [comment]
Does starting via the menu/.desktop file work?

**Comment by deikatsuo** [comment]
no

**Comment by Alexander-Wilms** [comment]
When I run it from the app menu, or by executing `flatpak run --command=io.elementary.code io.elementary.code` it works, but when I execute `flatpak run io.elementary.code`, I get this error:

```
Traceback (most recent call last):
  File "/app/bin/csv2rdf", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by TingPing** [comment]
> Traceback (most recent call last):
>   File "/app/bin/csv2rdf", line 5, in <module>
>     from pkg_resources import load_entry_point
> ImportError: No module named pkg_resources

Strange... is your runtime 2 months outdated?

**Comment by Alexander-Wilms** [comment]
That nicht actually be.
